version: '3.9'

services:
  web-backend:
    build: ./web_backend
    command: gunicorn main:app -w 2 --threads 2 -b 0.0.0.0:7777
    ports:
      - 7777:7777
  torchserve:
    image: pytorch/torchserve:latest-gpu
    command: torchserve --start --ts-config /torch-config.cnf --model-store /torch_model_dir --models bart=bart-large-xsum.mar whisper=whisper-base.mar
    volumes:
     - ./torch_model_dir:/torch_model_dir
     - ./torch-config.cnf:/torch-config.cnf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
