version: '3.9'

services:
  flask:
    build: ./flask
    environment:
      MOCK_ML_MODELS: "false"
      POSTGRES_DB_URL: "postgresql://postgres:postgres@postgres:5432/"
      FLASK_SECRET_KEY: "[YOUR_SECRET_KEY]"
      ETHERPAD_API_KEY: "[YOUR ETHERPAD API KEY]"
      ETHERPAD_API_URL: "http://etherpad:9001/api"
      ETHERPAD_URL: "https://etherpad.kmjec.cz"
      TORCHSERVE_MANAGEMENT_URL: "http://torchserve:8085"
      PYTHONBUFFERED: 1
    command: gunicorn main:app -w 2 --threads 2 -b 0.0.0.0:7777 --timeout 600
    depends_on: 
      - rabbitmq
      - postgres
    ports:
      - 7777:7777

  trsc-worker:
    build: ./transcription_worker
    environment:
      MOCK_ML_MODELS: "false"
      WHISPER_MODEL: "medium.en"
    command: python transcription_worker.py
    depends_on:
      - rabbitmq
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  summ-worker:
    build: ./summarization_worker
    environment:
      MOCK_ML_MODELS: "false"
      TORCH_BACKEND_URL: "http://torchserve:8084"
    command: python summarization_worker.py
    depends_on:
      - rabbitmq

  torchserve:
    build: ./torchserve
    command: torchserve --start --ts-config /torch-config.cnf --model-store /torch_model_dir --models flan-t5=flan-t5-base-samsum.mar bart=lidiya-bart.mar
    volumes:
     - ./torch_model_dir:/torch_model_dir
     - ./torch-config.cnf:/torch-config.cnf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgres:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgres/data
      - ./flask/db/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql

  etherpad:
    build: ./etherpad-lite
    ports:
      - 9001:9001
    environment:
      TITLE: Minuteman
      DEFAULT_PAD_TEXT: "Welcome to Minuteman!"
      ADMIN_PASSWORD: kalsfdjalkvcdjcslajads
      ADMIN_USER: admin
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_CHARSET: utf8mb4
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

volumes:
  db:
    driver: local
